// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitUHz5zXFbwummBv1HCfrQjYLRQorxQI',
    appId: '1:316987962943:web:8c39d0431c001b08b2ea8a',
    messagingSenderId: '316987962943',
    projectId: 'fir-fcf53',
    authDomain: 'fir-fcf53.firebaseapp.com',
    storageBucket: 'fir-fcf53.appspot.com',
    measurementId: 'G-3C3MPZ47LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWR3QwvRAz3xPtWcAxul2113i7UfSKArY',
    appId: '1:316987962943:android:83dc79dc7404c9d9b2ea8a',
    messagingSenderId: '316987962943',
    projectId: 'fir-fcf53',
    storageBucket: 'fir-fcf53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Qpg1y_A1wCwAvWR9U2ITtATiI2lIXX8',
    appId: '1:316987962943:ios:06abacf48f257261b2ea8a',
    messagingSenderId: '316987962943',
    projectId: 'fir-fcf53',
    storageBucket: 'fir-fcf53.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Qpg1y_A1wCwAvWR9U2ITtATiI2lIXX8',
    appId: '1:316987962943:ios:42024a6de22981fab2ea8a',
    messagingSenderId: '316987962943',
    projectId: 'fir-fcf53',
    storageBucket: 'fir-fcf53.appspot.com',
    iosBundleId: 'com.example.amazonClone.RunnerTests',
  );
}
